version: '3.4'

services:
  src:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
